# Generated by Django 4.1.1 on 2022-10-04 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examinate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='examID',
            new_name='exam_id',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='examName',
            new_name='exam_name',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='examPhotoFileName',
            new_name='exam_photo_name',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='examScore',
            new_name='exam_score',
        ),
    ]
